/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BarcodeRouteImport } from './routes/barcode'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as LaporanReportRouteImport } from './routes/laporan.$report'
import { Route as MasterSectionRouteImport } from './routes/master.$section'
import { Route as OpnameSectionRouteImport } from './routes/opname.$section'
import { Route as PengadaanSectionRouteImport } from './routes/pengadaan.$section'
import { Route as PersediaanAdjustmentRouteImport } from './routes/persediaan.adjustment'
import { Route as PersediaanKartuStockRouteImport } from './routes/persediaan.kartu-stock'
import { Route as PersediaanMutasiRouteImport } from './routes/persediaan.mutasi'
import { Route as PersediaanNilaiRouteImport } from './routes/persediaan.nilai'
import { Route as PersediaanStockRouteImport } from './routes/persediaan.stock'
import { Route as PersediaanStockMinimumRouteImport } from './routes/persediaan.stock-minimum'
import { Route as SystemSectionRouteImport } from './routes/system.$section'
import { Route as TransaksiSectionRouteImport } from './routes/transaksi.$section'
import { Route as TransaksiKeluarRouteImport } from './routes/transaksi.keluar'
import { Route as TransaksiMasukRouteImport } from './routes/transaksi.masuk'
import { Route as TransaksiTransferRouteImport } from './routes/transaksi.transfer'
import { Route as MasterBarangIndexRouteImport } from './routes/master.barang.index'
import { Route as MasterBarangIdRouteImport } from './routes/master.barang.$id'
import { Route as TransaksiEntriSectionRouteImport } from './routes/transaksi.entri.$section'
import { Route as TransaksiEntriSectionIdRouteImport } from './routes/transaksi.entri.$section.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BarcodeRoute = BarcodeRouteImport.update({
  id: '/barcode',
  path: '/barcode',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanReportRoute = LaporanReportRouteImport.update({
  id: '/laporan/$report',
  path: '/laporan/$report',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterSectionRoute = MasterSectionRouteImport.update({
  id: '/master/$section',
  path: '/master/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const OpnameSectionRoute = OpnameSectionRouteImport.update({
  id: '/opname/$section',
  path: '/opname/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const PengadaanSectionRoute = PengadaanSectionRouteImport.update({
  id: '/pengadaan/$section',
  path: '/pengadaan/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const PersediaanAdjustmentRoute = PersediaanAdjustmentRouteImport.update({
  id: '/persediaan/adjustment',
  path: '/persediaan/adjustment',
  getParentRoute: () => rootRouteImport,
} as any)
const PersediaanKartuStockRoute = PersediaanKartuStockRouteImport.update({
  id: '/persediaan/kartu-stock',
  path: '/persediaan/kartu-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const PersediaanMutasiRoute = PersediaanMutasiRouteImport.update({
  id: '/persediaan/mutasi',
  path: '/persediaan/mutasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PersediaanNilaiRoute = PersediaanNilaiRouteImport.update({
  id: '/persediaan/nilai',
  path: '/persediaan/nilai',
  getParentRoute: () => rootRouteImport,
} as any)
const PersediaanStockRoute = PersediaanStockRouteImport.update({
  id: '/persediaan/stock',
  path: '/persediaan/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const PersediaanStockMinimumRoute = PersediaanStockMinimumRouteImport.update({
  id: '/persediaan/stock-minimum',
  path: '/persediaan/stock-minimum',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemSectionRoute = SystemSectionRouteImport.update({
  id: '/system/$section',
  path: '/system/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const TransaksiSectionRoute = TransaksiSectionRouteImport.update({
  id: '/transaksi/$section',
  path: '/transaksi/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const TransaksiKeluarRoute = TransaksiKeluarRouteImport.update({
  id: '/transaksi/keluar',
  path: '/transaksi/keluar',
  getParentRoute: () => rootRouteImport,
} as any)
const TransaksiMasukRoute = TransaksiMasukRouteImport.update({
  id: '/transaksi/masuk',
  path: '/transaksi/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const TransaksiTransferRoute = TransaksiTransferRouteImport.update({
  id: '/transaksi/transfer',
  path: '/transaksi/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterBarangIndexRoute = MasterBarangIndexRouteImport.update({
  id: '/master/barang/',
  path: '/master/barang/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterBarangIdRoute = MasterBarangIdRouteImport.update({
  id: '/master/barang/$id',
  path: '/master/barang/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TransaksiEntriSectionRoute = TransaksiEntriSectionRouteImport.update({
  id: '/transaksi/entri/$section',
  path: '/transaksi/entri/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const TransaksiEntriSectionIdRoute = TransaksiEntriSectionIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TransaksiEntriSectionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/barcode': typeof BarcodeRoute
  '/login': typeof LoginRoute
  '/pengaturan': typeof PengaturanRoute
  '/laporan/$report': typeof LaporanReportRoute
  '/master/$section': typeof MasterSectionRoute
  '/opname/$section': typeof OpnameSectionRoute
  '/pengadaan/$section': typeof PengadaanSectionRoute
  '/persediaan/adjustment': typeof PersediaanAdjustmentRoute
  '/persediaan/kartu-stock': typeof PersediaanKartuStockRoute
  '/persediaan/mutasi': typeof PersediaanMutasiRoute
  '/persediaan/nilai': typeof PersediaanNilaiRoute
  '/persediaan/stock': typeof PersediaanStockRoute
  '/persediaan/stock-minimum': typeof PersediaanStockMinimumRoute
  '/system/$section': typeof SystemSectionRoute
  '/transaksi/$section': typeof TransaksiSectionRoute
  '/transaksi/keluar': typeof TransaksiKeluarRoute
  '/transaksi/masuk': typeof TransaksiMasukRoute
  '/transaksi/transfer': typeof TransaksiTransferRoute
  '/master/barang/$id': typeof MasterBarangIdRoute
  '/transaksi/entri/$section': typeof TransaksiEntriSectionRouteWithChildren
  '/master/barang/': typeof MasterBarangIndexRoute
  '/transaksi/entri/$section/$id': typeof TransaksiEntriSectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/barcode': typeof BarcodeRoute
  '/login': typeof LoginRoute
  '/pengaturan': typeof PengaturanRoute
  '/laporan/$report': typeof LaporanReportRoute
  '/master/$section': typeof MasterSectionRoute
  '/opname/$section': typeof OpnameSectionRoute
  '/pengadaan/$section': typeof PengadaanSectionRoute
  '/persediaan/adjustment': typeof PersediaanAdjustmentRoute
  '/persediaan/kartu-stock': typeof PersediaanKartuStockRoute
  '/persediaan/mutasi': typeof PersediaanMutasiRoute
  '/persediaan/nilai': typeof PersediaanNilaiRoute
  '/persediaan/stock': typeof PersediaanStockRoute
  '/persediaan/stock-minimum': typeof PersediaanStockMinimumRoute
  '/system/$section': typeof SystemSectionRoute
  '/transaksi/$section': typeof TransaksiSectionRoute
  '/transaksi/keluar': typeof TransaksiKeluarRoute
  '/transaksi/masuk': typeof TransaksiMasukRoute
  '/transaksi/transfer': typeof TransaksiTransferRoute
  '/master/barang/$id': typeof MasterBarangIdRoute
  '/transaksi/entri/$section': typeof TransaksiEntriSectionRouteWithChildren
  '/master/barang': typeof MasterBarangIndexRoute
  '/transaksi/entri/$section/$id': typeof TransaksiEntriSectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/barcode': typeof BarcodeRoute
  '/login': typeof LoginRoute
  '/pengaturan': typeof PengaturanRoute
  '/laporan/$report': typeof LaporanReportRoute
  '/master/$section': typeof MasterSectionRoute
  '/opname/$section': typeof OpnameSectionRoute
  '/pengadaan/$section': typeof PengadaanSectionRoute
  '/persediaan/adjustment': typeof PersediaanAdjustmentRoute
  '/persediaan/kartu-stock': typeof PersediaanKartuStockRoute
  '/persediaan/mutasi': typeof PersediaanMutasiRoute
  '/persediaan/nilai': typeof PersediaanNilaiRoute
  '/persediaan/stock': typeof PersediaanStockRoute
  '/persediaan/stock-minimum': typeof PersediaanStockMinimumRoute
  '/system/$section': typeof SystemSectionRoute
  '/transaksi/$section': typeof TransaksiSectionRoute
  '/transaksi/keluar': typeof TransaksiKeluarRoute
  '/transaksi/masuk': typeof TransaksiMasukRoute
  '/transaksi/transfer': typeof TransaksiTransferRoute
  '/master/barang/$id': typeof MasterBarangIdRoute
  '/transaksi/entri/$section': typeof TransaksiEntriSectionRouteWithChildren
  '/master/barang/': typeof MasterBarangIndexRoute
  '/transaksi/entri/$section/$id': typeof TransaksiEntriSectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/barcode'
    | '/login'
    | '/pengaturan'
    | '/laporan/$report'
    | '/master/$section'
    | '/opname/$section'
    | '/pengadaan/$section'
    | '/persediaan/adjustment'
    | '/persediaan/kartu-stock'
    | '/persediaan/mutasi'
    | '/persediaan/nilai'
    | '/persediaan/stock'
    | '/persediaan/stock-minimum'
    | '/system/$section'
    | '/transaksi/$section'
    | '/transaksi/keluar'
    | '/transaksi/masuk'
    | '/transaksi/transfer'
    | '/master/barang/$id'
    | '/transaksi/entri/$section'
    | '/master/barang/'
    | '/transaksi/entri/$section/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/barcode'
    | '/login'
    | '/pengaturan'
    | '/laporan/$report'
    | '/master/$section'
    | '/opname/$section'
    | '/pengadaan/$section'
    | '/persediaan/adjustment'
    | '/persediaan/kartu-stock'
    | '/persediaan/mutasi'
    | '/persediaan/nilai'
    | '/persediaan/stock'
    | '/persediaan/stock-minimum'
    | '/system/$section'
    | '/transaksi/$section'
    | '/transaksi/keluar'
    | '/transaksi/masuk'
    | '/transaksi/transfer'
    | '/master/barang/$id'
    | '/transaksi/entri/$section'
    | '/master/barang'
    | '/transaksi/entri/$section/$id'
  id:
    | '__root__'
    | '/'
    | '/barcode'
    | '/login'
    | '/pengaturan'
    | '/laporan/$report'
    | '/master/$section'
    | '/opname/$section'
    | '/pengadaan/$section'
    | '/persediaan/adjustment'
    | '/persediaan/kartu-stock'
    | '/persediaan/mutasi'
    | '/persediaan/nilai'
    | '/persediaan/stock'
    | '/persediaan/stock-minimum'
    | '/system/$section'
    | '/transaksi/$section'
    | '/transaksi/keluar'
    | '/transaksi/masuk'
    | '/transaksi/transfer'
    | '/master/barang/$id'
    | '/transaksi/entri/$section'
    | '/master/barang/'
    | '/transaksi/entri/$section/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BarcodeRoute: typeof BarcodeRoute
  LoginRoute: typeof LoginRoute
  PengaturanRoute: typeof PengaturanRoute
  LaporanReportRoute: typeof LaporanReportRoute
  MasterSectionRoute: typeof MasterSectionRoute
  OpnameSectionRoute: typeof OpnameSectionRoute
  PengadaanSectionRoute: typeof PengadaanSectionRoute
  PersediaanAdjustmentRoute: typeof PersediaanAdjustmentRoute
  PersediaanKartuStockRoute: typeof PersediaanKartuStockRoute
  PersediaanMutasiRoute: typeof PersediaanMutasiRoute
  PersediaanNilaiRoute: typeof PersediaanNilaiRoute
  PersediaanStockRoute: typeof PersediaanStockRoute
  PersediaanStockMinimumRoute: typeof PersediaanStockMinimumRoute
  SystemSectionRoute: typeof SystemSectionRoute
  TransaksiSectionRoute: typeof TransaksiSectionRoute
  TransaksiKeluarRoute: typeof TransaksiKeluarRoute
  TransaksiMasukRoute: typeof TransaksiMasukRoute
  TransaksiTransferRoute: typeof TransaksiTransferRoute
  MasterBarangIdRoute: typeof MasterBarangIdRoute
  TransaksiEntriSectionRoute: typeof TransaksiEntriSectionRouteWithChildren
  MasterBarangIndexRoute: typeof MasterBarangIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barcode': {
      id: '/barcode'
      path: '/barcode'
      fullPath: '/barcode'
      preLoaderRoute: typeof BarcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan/$report': {
      id: '/laporan/$report'
      path: '/laporan/$report'
      fullPath: '/laporan/$report'
      preLoaderRoute: typeof LaporanReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/$section': {
      id: '/master/$section'
      path: '/master/$section'
      fullPath: '/master/$section'
      preLoaderRoute: typeof MasterSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opname/$section': {
      id: '/opname/$section'
      path: '/opname/$section'
      fullPath: '/opname/$section'
      preLoaderRoute: typeof OpnameSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengadaan/$section': {
      id: '/pengadaan/$section'
      path: '/pengadaan/$section'
      fullPath: '/pengadaan/$section'
      preLoaderRoute: typeof PengadaanSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persediaan/adjustment': {
      id: '/persediaan/adjustment'
      path: '/persediaan/adjustment'
      fullPath: '/persediaan/adjustment'
      preLoaderRoute: typeof PersediaanAdjustmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persediaan/kartu-stock': {
      id: '/persediaan/kartu-stock'
      path: '/persediaan/kartu-stock'
      fullPath: '/persediaan/kartu-stock'
      preLoaderRoute: typeof PersediaanKartuStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persediaan/mutasi': {
      id: '/persediaan/mutasi'
      path: '/persediaan/mutasi'
      fullPath: '/persediaan/mutasi'
      preLoaderRoute: typeof PersediaanMutasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persediaan/nilai': {
      id: '/persediaan/nilai'
      path: '/persediaan/nilai'
      fullPath: '/persediaan/nilai'
      preLoaderRoute: typeof PersediaanNilaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persediaan/stock': {
      id: '/persediaan/stock'
      path: '/persediaan/stock'
      fullPath: '/persediaan/stock'
      preLoaderRoute: typeof PersediaanStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persediaan/stock-minimum': {
      id: '/persediaan/stock-minimum'
      path: '/persediaan/stock-minimum'
      fullPath: '/persediaan/stock-minimum'
      preLoaderRoute: typeof PersediaanStockMinimumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/$section': {
      id: '/system/$section'
      path: '/system/$section'
      fullPath: '/system/$section'
      preLoaderRoute: typeof SystemSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaksi/$section': {
      id: '/transaksi/$section'
      path: '/transaksi/$section'
      fullPath: '/transaksi/$section'
      preLoaderRoute: typeof TransaksiSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaksi/keluar': {
      id: '/transaksi/keluar'
      path: '/transaksi/keluar'
      fullPath: '/transaksi/keluar'
      preLoaderRoute: typeof TransaksiKeluarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaksi/masuk': {
      id: '/transaksi/masuk'
      path: '/transaksi/masuk'
      fullPath: '/transaksi/masuk'
      preLoaderRoute: typeof TransaksiMasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaksi/transfer': {
      id: '/transaksi/transfer'
      path: '/transaksi/transfer'
      fullPath: '/transaksi/transfer'
      preLoaderRoute: typeof TransaksiTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/barang/': {
      id: '/master/barang/'
      path: '/master/barang'
      fullPath: '/master/barang/'
      preLoaderRoute: typeof MasterBarangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/barang/$id': {
      id: '/master/barang/$id'
      path: '/master/barang/$id'
      fullPath: '/master/barang/$id'
      preLoaderRoute: typeof MasterBarangIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaksi/entri/$section': {
      id: '/transaksi/entri/$section'
      path: '/transaksi/entri/$section'
      fullPath: '/transaksi/entri/$section'
      preLoaderRoute: typeof TransaksiEntriSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaksi/entri/$section/$id': {
      id: '/transaksi/entri/$section/$id'
      path: '/$id'
      fullPath: '/transaksi/entri/$section/$id'
      preLoaderRoute: typeof TransaksiEntriSectionIdRouteImport
      parentRoute: typeof TransaksiEntriSectionRoute
    }
  }
}

interface TransaksiEntriSectionRouteChildren {
  TransaksiEntriSectionIdRoute: typeof TransaksiEntriSectionIdRoute
}

const TransaksiEntriSectionRouteChildren: TransaksiEntriSectionRouteChildren = {
  TransaksiEntriSectionIdRoute: TransaksiEntriSectionIdRoute,
}

const TransaksiEntriSectionRouteWithChildren =
  TransaksiEntriSectionRoute._addFileChildren(
    TransaksiEntriSectionRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BarcodeRoute: BarcodeRoute,
  LoginRoute: LoginRoute,
  PengaturanRoute: PengaturanRoute,
  LaporanReportRoute: LaporanReportRoute,
  MasterSectionRoute: MasterSectionRoute,
  OpnameSectionRoute: OpnameSectionRoute,
  PengadaanSectionRoute: PengadaanSectionRoute,
  PersediaanAdjustmentRoute: PersediaanAdjustmentRoute,
  PersediaanKartuStockRoute: PersediaanKartuStockRoute,
  PersediaanMutasiRoute: PersediaanMutasiRoute,
  PersediaanNilaiRoute: PersediaanNilaiRoute,
  PersediaanStockRoute: PersediaanStockRoute,
  PersediaanStockMinimumRoute: PersediaanStockMinimumRoute,
  SystemSectionRoute: SystemSectionRoute,
  TransaksiSectionRoute: TransaksiSectionRoute,
  TransaksiKeluarRoute: TransaksiKeluarRoute,
  TransaksiMasukRoute: TransaksiMasukRoute,
  TransaksiTransferRoute: TransaksiTransferRoute,
  MasterBarangIdRoute: MasterBarangIdRoute,
  TransaksiEntriSectionRoute: TransaksiEntriSectionRouteWithChildren,
  MasterBarangIndexRoute: MasterBarangIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
